--check兼容windows
node-modules/autod pull request #46
Opened 2020-10-27 12:38 UTC by weijiafu14

2020-10-27 12:39 UTC, weijiafu14 commented
使用的时候windows环境check 会报错

2020-10-27 12:41 UTC, weijiafu14 commented
使用的时候windows环境会报错，一个是判断 node_modules ，一个是 判断 exclude 和 test的地方和windows不兼容
https://github.com/node-modules/connection/pull/6/checks?check_run_id=1313681469

2020-10-29 01:53 UTC, atian25 requested changes

2020-10-29 01:53 UTC, atian25 commented on index.js
> +      options.exclude = options.exclude.concat(glob.sync(path.join(options.root, e)).map(path.normalize));
这个地方感觉是不需要的， glob 应该处理了。

2020-10-29 01:53 UTC, atian25 commented on .github/workflows/nodejs.yml
> +# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
这个 action 先单独提个 PR？ 这样的话我们就能看你其他修改的 win ci 测试结果了。

2020-10-30 04:30 UTC, weijiafu14 commented on index.js
> +      options.exclude = options.exclude.concat(glob.sync(path.join(options.root, e)).map(path.normalize));
这里glob 会处理成 C://xxx/xx/xxx 这种形式
不兼容的是底下的一个：
`_contains(path, matchs) {
    for (const match of matchs) {
      if (path.startsWith(match)) return true;
    }
  }`
这里会有不兼容，看path 的API 没想到很好的方式
或者处理成：
`path.relative(from, to).indexOf('..')>0`

2020-10-30 04:32 UTC, weijiafu14 commented on .github/workflows/nodejs.yml
> +# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
好的好的，我先提一个这个

2020-11-02 03:28 UTC, weijiafu14 commented on .github/workflows/nodejs.yml
> +# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
https://github.com/weijiafu14/autod/pull/2
在我仓库里测过里，确实改了之后都可以过

2020-11-03 06:17 UTC, atian25 commented
那个合并了，这个要 rebase 下

2020-11-03 06:59 UTC, closed without merging